### ISSUE TITLE
Monadic operations don't support `void` returns

### ISSUE THREAD

**Issue by TartanLlama** [SuperV1234/scelta#13]
This is something of a niche feature, but I like it, so thought I'd suggest it anyway :smile: 

If you support mapping functions which return void then you can compose functions which have side effects:

```
optional<int> o = maybe_get_int();
o  | and_then(do_thing)
   | map(log); //only happens if both maybe_get_int() and do_thing returned values
```

I do this in my library by translating `void` returns to `tl::monostate`. Since you're using C++17, you could just use `std::monostate`.

**Comment by SuperV1234** [comment]
Will look into this.

**Comment by SuperV1234** [comment]
This only makes sense for `map` and `map_or_else`, correct?

**Comment by TartanLlama** [comment]
Yep
