### ISSUE TITLE
Deducing arity of generic lambda

### ISSUE THREAD

**Issue by no-more-secrets** [SuperV1234/scelta#15]
Do I understand correctly that the Scelta library could benefit from a solution to this problem?  Is it still unsolved?
David

**Comment by dpacbach** [comment]
If you had an implementation of:

template<typename Lambda>
constexpr bool is_binary_op_v = ...;

would that solve the problem?

**Comment by dpacbach** [comment]
Actually you can ignore -- just this talk:
https://www.youtube.com/watch?v=3KyW5Ve3LtI
which answers my questions.
